services:
  database:
    image: mongo
  
  redis:
    image: redis

  server:
    build: .
    depends_on:
      - database
      - redis
    ports:
      - 8050:8050
    environment:
      DATABASE_URI: 'mongodb://database:27017/dev'
